[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/500.html"
  to = "/500.html"
  status = 500

[[redirects]]
  from = "/502.html"
  to = "/502.html"
  status = 502

[[redirects]]
  from = "/503.html"
  to = "/503.html"
  status = 503

[[redirects]]
  from = "/504.html"
  to = "/504.html"
  status = 504
